---

- name: Deploy PHP Application and create Cron jobs on Slave node
  hosts: slave-server
  tasks:
    #Create a cron job to check the server’s uptime every 12 am.
    - name: Create a cron job to check the uptime of the server every 12 am
      cron:
        name: schedule to check uptime server
        minute: "0"
        hour: "0"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/usr/bin/uptime > /var/log/uptime.log 2>&1"
        state: present

    # Copy the bash script into the ansible directory and execute     
    - name: copy bash script named "slave-deploy.sh"
      copy:
        src: /home/vagrant/slave-deploy.sh
        dest: /home/vagrant/Ansible/slave-deploy.sh
        mode: '0777'

    - name: Execute bash script
      shell: bash /home/vagrant/Ansible/slave-deploy.sh
      ignore_errors: yes

# Verify PHP Application Accessibility
    - name: Make a request to the PHP page
      ansible.builtin.uri:
        url: http://{{ ansible_host }}
        return_content: yes
      register: page_content

    - name: Check if "Laracast" is in the page contents
      ansible.builtin.fail:
        msg: "The page does not contain 'Laracast'"
      when: "'Laracast' not in page_content.content|default('')"

    - name: Report success
      debug:
        msg: "The page returned successfully and contains 'Laracast'"
